name = "cloudhire"
compatibility_date = "2025-07-19"
pages_build_output_dir = ".next"

# Shared variables for all environments
[vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"

# D1 database binding (commented out until database is created)
# [[d1_databases]]
# binding = "DB"
# database_name = "exam-db"
# database_id = "your-d1-database-id"

# Production environment configuration
[env.production]
vars = { AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/" }

# Preview environment configuration  
[env.preview]
vars = { AI_GRADER_WORKER_URL = "https://ai-grader-worker-preview.youraccount.workers.dev/" }
