name = "exam-web-app"
compatibility_date = "2024-01-15"

[env.production]
name = "exam-web-app-production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "exam_reports"
database_id = "your-d1-database-id"

[env.development]
name = "exam-web-app-development"

[[env.development.d1_databases]]
binding = "DB"
database_name = "exam_reports_dev"
database_id = "your-dev-d1-database-id"

# Python Worker configuration
[[workers]]
name = "ai-grader-worker"
main = "python/grader.py"
compatibility_date = "2024-01-15"

[workers.vars]
# Set XAI_API_KEY in Cloudflare dashboard
