name = "cloudhire"
compatibility_date = "2025-07-19"
pages_build_output_dir = ".next"

# Shared variables for all environments
[vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"

# D1 database binding (will be configured after database creation)
# [[d1_databases]]
# binding = "DB"
# database_name = "exam-db"
# database_id = "your-d1-database-id"

# Optional: Preview environment overrides (for non-main branches)
[env.preview.vars]
AI_GRADER_WORKER_URL = "https://staging-ai-grader.youraccount.workers.dev/"

# Optional: Production environment overrides (for main branch)
[env.production.vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"
