name = "cloudhire"
compatibility_date = "2025-07-19"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"  # OpenNext build output

# Environment variables (secrets should be set via wrangler secret put)
[vars]
SITE_URL = "https://cloudhire.avschaefer.workers.dev"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "cloudhire-db"
database_id = "30768915-bb91-4955-a0a8-99e96742c717"
migrations_dir = "migrations"

# Build configuration
[build]
command = "npm run build:opennext"
watch_dir = "src"

# Deployment configuration
[deploy]
upload_dir = ".open-next"