name = "cloudhire"
compatibility_date = "2025-07-19"
pages_build_output_dir = ".next"

# This is for Pages deployment
[env.production]
name = "cloudhire-production"

[env.development] 
name = "cloudhire-development"

# D1 database configuration will be set in Cloudflare Pages dashboard
# Environment variables will be set in Pages dashboard
