name = "cloudhire"
compatibility_date = "2025-07-19"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "exam-db"
database_id = "placeholder-will-be-replaced-after-d1-creation"

[vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"

[env.preview.vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker-preview.youraccount.workers.dev/"

[env.production.vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"
