name = "cloudhire"
compatibility_date = "2025-07-19"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "exam-db"
database_id = "your-d1-id"  # Update this after D1 creation

[vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"  # Update after Worker deployment
NEXT_PUBLIC_SITE_URL = "https://cloudhire.app"  # For client-side usage
