name = "cloudhire"
compatibility_date = "2025-07-19"
pages_build_output_dir = ".next"

[vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"

[env.preview.vars]
AI_GRADER_WORKER_URL = "https://staging-ai-grader.youraccount.workers.dev/"

[env.production.vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"
