name = "cloudhire"
compatibility_date = "2025-01-19"
pages_build_output_dir = ".next"

# Temporarily comment out D1 binding until database is created
# [[d1_databases]]
# binding = "DB"
# database_name = "exam-db"
# database_id = "your-d1-database-id-here"

[vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"

[env.preview.vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker-preview.youraccount.workers.dev/"

[env.production.vars]
AI_GRADER_WORKER_URL = "https://ai-grader-worker.youraccount.workers.dev/"
