import { generateEmailSubject, generateEmailPreview } from "@/utils/email-utils"
import type { ReportData } from "@/lib/d1"

export async function sendReportEmail(
  htmlReport: string,
  candidateName: string,
  position: string,
  reportData?: ReportData,
): Promise<boolean> {
  try {
    const subject = generateEmailSubject(candidateName, position)

    const emailPayload = {
      subject,
      htmlContent: htmlReport,
      reportData, // Include report data for D1 storage
    }

    console.log("Sending report email via API route...")

    const response = await fetch("/api/send-email", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(emailPayload),
    })

    const result = await response.json()

    if (!response.ok) {
      console.error("Email API error:", result)
      return false
    }

    console.log("Email sent successfully:", result)
    return true
  } catch (error) {
    console.error("Failed to send report email:", error)
    return false
  }
}

export function generateEmailTemplate(
  candidateName: string,
  position: string,
  overallScore: number,
  recommendation: string,
  reportUrl?: string,
): string {
  const preview = generateEmailPreview(overallScore, recommendation)

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${generateEmailSubject(candidateName, position)}</title>
    </head>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
        <h1 style="color: #2c3e50; margin: 0;">Technical Assessment Results</h1>
        <p style="margin: 10px 0 0 0; color: #666;">${preview}</p>
      </div>
      
      <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #e9ecef;">
        <h2 style="color: #2c3e50; margin-top: 0;">Candidate: ${candidateName}</h2>
        <p><strong>Position:</strong> ${position}</p>
        <p><strong>Overall Score:</strong> ${overallScore}%</p>
        <p><strong>Recommendation:</strong> <span style="color: ${
          recommendation === "HIRE" ? "#28a745" : recommendation === "CONSIDER" ? "#ffc107" : "#dc3545"
        }; font-weight: bold;">${recommendation}</span></p>
        
        ${
          reportUrl
            ? `
        <div style="margin-top: 20px; padding: 15px; background: #e3f2fd; border-radius: 4px;">
          <p style="margin: 0;"><strong>View Full Report:</strong></p>
          <a href="${reportUrl}" style="color: #1976d2; text-decoration: none;">${reportUrl}</a>
        </div>
        `
            : ""
        }
      </div>
      
      <div style="margin-top: 20px; padding: 15px; background: #f8f9fa; border-radius: 4px; font-size: 14px; color: #666;">
        <p style="margin: 0;">This assessment was automatically generated by CloudHire's AI evaluation system.</p>
      </div>
    </body>
    </html>
  `
}
